// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://doiohknwkitbvztofwzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvaW9oa253a2l0YnZ6dG9md3pjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMjAwMzUsImV4cCI6MjA1NjU5NjAzNX0.OCvrVto-zRrDHzirMEEPRSd4TbIdIcPS1b0c1xTQCFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);